### ISSUE TITLE
White List

### ISSUE THREAD

**Issue by rkovachev88** [velivelo/insta-bot#1]
Hello,

Could you include a white list for the followers?

Thank you!

**Comment by velivelo** [comment]
Mmh, can you explain what you mean by that please ?

**Comment by rkovachev88** [comment]
Like the blacklist but the users from the whitelist shouldn't be unfollowed.

**Comment by velivelo** [comment]
I add it tomorrow.

**Comment by velivelo** [comment]
Done (I have totaly changed automod.py).

**Comment by rkovachev88** [comment]
It can't start now.

**Comment by rkovachev88** [comment]
There are two "end_at" and I have to change them both.

How to disable commenting, liking, following and unfollowing one by one? In case that I need the bot to do different tasks.

**Comment by velivelo** [comment]
There is only one "end_at"... If you talk about the one in start method parameter, it is only the default value if not defined at the call. 

I suggest you to read the README : you can disable for exemple commenting by setting "comment_ratio" to 0.

**Comment by rkovachev88** [comment]
I just did that. Thank you! But there is no way to stop unfollowing for all users?

**Comment by velivelo** [comment]
"add_to_unfollow_queue" to False.

**Comment by rkovachev88** [comment]
Will it unfollow my manually followed users then? And can it unfollow all of my users except the ones in the whitelist?

**Comment by velivelo** [comment]
No it won't.

**Comment by rkovachev88** [comment]
Ok, I understand the logic now.
