### ISSUE TITLE
Sleeping times

### ISSUE THREAD

**Issue by rkovachev88** [velivelo/insta-bot#3]
Is there a way to set sleeping times?

**Comment by velivelo** [comment]
The sleeping time is the time_gap attribute in src/automod.py so you can set it when calling the method.

**Comment by rkovachev88** [comment]
I mean an interval - for example from 00 am till 07 am.

**Comment by velivelo** [comment]
Ah ok, no there isn't but I'll had it asap, its a good idea :)

**Comment by velivelo** [comment]
Done. start_at and end_at are datetime.datetime objects.

**Comment by rkovachev88** [comment]
It will be better if it can be set an hour to start/stop for everyday.  If I set it to start at 7 am and stop at 11 pm, it should make actions during this interval only. If I understand it right, now I have to set the date to start/stop. I want it to run every day, during the desired interval.

Sorry, I'm not a coder and can't understand all the lines.
