### ISSUE TITLE
The bot can't stop commenting and unfollowing

### ISSUE THREAD

**Issue by rkovachev88** [velivelo/insta-bot#4]
Even that the commenting and unfollowing are set to False, the bot continue to comment and unfollow.

**Comment by velivelo** [comment]
I've added an unfollow option where if set to `False` the bot won't add followed accounts to the unfollow_queue. But there is no way to prevent the bot from unfollow the accounts in the unfollow_queue. And if comment is set to `False`, the bot won't comment.

**Comment by rkovachev88** [comment]
I haven't change it at the end of the code for the comments. Now it won't comment.

Is there a way the bot to stop unfollow?
